cost_runner:
  feasible_map_topic: "/approach/feasible_map"
  transition_map_topic: "/approach/transition_count_map"
  target_point_topic: "/approach/target_point"
  grasp_targets_topic: "/approach/grasp_targets"
  grasp_status_topic: "/approach/grasp_status"
  robot_frame_id: "base"
  output_topic: "/approach/final_cost_map"
  arrow_topic: "/approach/best_cost_arrow"
  transform_timeout_sec: 0.1
  grasp_radius_m: 0.9
