cost_runner:
  feasible_map_topic: "feasible_map"
  transition_map_topic: "transition_count_map"
  target_point_topic: "/clicked_point"
  robot_frame_id: "base"
  output_topic: "final_cost_map"
  arrow_topic: "best_cost_arrow"
  transform_timeout_sec: 0.1
