planner:
  weight_goal_cost: 3.0
  weight_path_length: 1.0
  weight_clearance_penalty: 2.0
  clearance_penalty_power: 2.0
  minimum_clearance_ratio: 0.05
  allow_diagonal: true
  nearest_start_max_radius_cells: 5
  minimum_goal_distance_m: 0.0
  invalid_value: -1.0

planner_runner:
  feasible_map_topic: "/approach/feasible_map"
  clearance_map_topic: "/approach/clearance_map"
  final_cost_map_topic: "/approach/final_cost_map"
  robot_frame_id: "base"
  planning_score_topic: "/approach/planning_score_map"
  path_topic: "/approach/planned_path"
  goal_topic: "best_planning_goal"
  transform_timeout_sec: 0.1
