approach_map_runner_node:
  ros__parameters:
    input_cloud_topic: "/approach/aligned_cloud" # "/approach/accumulated_cloud"
    target_point_topic: "/approach/target_point"
    grasp_targets_topic: "/approach/grasp_targets"
    mapping_service_name: "/approach/mapping"
    map_frame_id: "map"
    obstacle_map_topic: "/approach/obstacle_map"
    nav2_obstacle_map_topic: "/approach/nav2_obstacle_map"
    feasible_map_topic: "/approach/feasible_map"
    nav2_feasible_map_topic: "/approach/nav2_feasible_map"
    clearance_map_topic: "/approach/clearance_map"
    transition_map_topic: "/approach/transition_count_map"
    robot_filter_frame_id: "base"
    use_initial_origin: false
    allow_origin_updates_after_first_click: false
    target_update_threshold_m: 2.0
    initial_origin_x_m: 0.0
    initial_origin_y_m: 0.0
    ground_z_min_m: -0.40
    ground_z_max_m: 0.10
    obstacle_z_min_m: 0.25
    obstacle_z_max_m: 1.50
    publish_heading_bin: 0
    clearance_display_cap_m: 1.5
    transform_timeout_sec: 0.1
    preprocess_remove_nan_enable: true
    preprocess_downsample_enable: true
    preprocess_outlier_removal_enable: true
    preprocess_voxel_leaf_size: 0.07
    outlier_mean_k: 20
    outlier_stddev_mul_thresh: 1.0
    robot_filter_enable: true
    robot_filter_x_min: -0.30
    robot_filter_x_max: 0.50
    robot_filter_y_min: -0.50
    robot_filter_y_max: 0.50
